export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const CHANGE_CART_OWNER = 'CHANGE_CART_OWNER';
export const CART_ORDER_REQUEST = 'CART_ORDER_REQUEST';
export const CART_ORDER_SUCCESS = 'CART_ORDER_SUCCESS';
export const CART_ORDER_FAILURE = 'CART_ORDER_FAILURE';